Added custom fail message

diff --git a/.github/workflows/branch_validator.yaml b/.github/workflows/branch_validator.yaml
--- a/.github/workflows/branch_validator.yaml
+++ b/.github/workflows/branch_validator.yaml
@@ -16,4 +16,10 @@ jobs:
         branch-name: "${{ github.ref }}" # The current branch where the workflow is running.
         validation-logic: "matches('YAS-\\d+-[A-Za-z]+')"
         trim-from-start: "refs/heads/"
-        fail-when-not-valid: true # Optional. Default is true.
+        fail-when-not-valid: false # Optional. Default is true.
+    
+    - name: Output Result
+      if: ${{ steps.validate-branch.outputs.valid-branch }} = 'false'
+      run: |
+        echo "The branch name '${{ github.ref }}' is not valid. Name the branch in the format YAS-<number>-<description>."
+        exit 1; # Fails the workflow
